package PART_II_OOP.Day45.Exceptions_GroupStudy;

public class A_BadArray {

public static void main(String[] args) {
		
		int[] number = {1,2,3};
		
		for(int i=0;i<=number.length;i++) {
			System.out.println(number[i]);
		}
		
		System.out.println("Learning exception");
		

	}

	
}
